### PR TITLE
fix constraints of vertex_add_path_sum

### LINKED ISSUE #125: [問題案] Vertex Add Path Sum (vertex_add_path_sum)
# 問題概要

木が与えられる。

- 0 p x: a_p += x
- 1 u v: u, v間のパス(両端含む)のaのsum

## 入力

```
N Q
a_0 a_1 ... a_{N - 1}
u_0 v_0
u_1 v_1
:
u_{N - 2} v_{N - 2}
Query0
Query1
:
Query_{Q - 1}
```

## 出力

```
```

## 制約

- 1 <= N <= 200,000

### PR DESCRIPTION
**Pull request by yosupo06**
fix #125

### CODE REVIEW

File: datastructure/vertex_add_path_sum/verifier.cpp [hunk 1]
```diff
@@ -53,7 +54,7 @@ int main() {
         if (t == 0) {
             inf.readInt(0, n - 1, "p");
             inf.readSpace();
-            inf.readInt(0, 1'000'000'000, "x");
+            inf.readInt(0, A_X_MAX, "x");
```
Comment (yosupo06) [inline datastructure/vertex_add_path_sum/verifier.cpp]:
```suggestion
            inf.readInt(0, A_AND_X_MAX, "x");
```
